# Generated by Django 3.1.6 on 2021-04-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['pk', 'school'],
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['school', 's_class'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='schedule.school', verbose_name='Школа'),
            preserve_default=False,
        ),
    ]
