# Generated by Django 3.1.6 on 2021-04-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210402_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['pk', 'school_name'], 'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_school'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school',
            new_name='school_name',
        ),

    ]
