# Generated by Django 3.1.6 on 2021-04-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210402_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_last_name'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),


    ]
